---
title: "Results Figures"
author: "Yomna Eid"
date: "2025-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stars)
library(osmdata)
library(ggplot2)

load("sampling.rda")

imp20m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_20m.tif$", recursive = TRUE,  full.names = TRUE)
imp40m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_40m.tif$", recursive = TRUE,  full.names = TRUE)
imp80m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_80m.tif$", recursive = TRUE,  full.names = TRUE)
imp100m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_100m.tif$", recursive = TRUE,  full.names = TRUE)
imp200m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_200m.tif$", recursive = TRUE,  full.names = TRUE)
imp400m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_400m.tif$", recursive = TRUE,  full.names = TRUE)
imp800m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_800m.tif$", recursive = TRUE,  full.names = TRUE)
imp1000m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_1000m.tif$", recursive = TRUE,  full.names = TRUE)
imp2000m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_2000m.tif$", recursive = TRUE,  full.names = TRUE)
imp4000m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_4000m.tif$", recursive = TRUE,  full.names = TRUE)
imp8000m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_8000m.tif$", recursive = TRUE,  full.names = TRUE)
imp10000m_files <- list.files(path = r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\)", pattern = "\\_10000m.tif$", recursive = TRUE,  full.names = TRUE)
```


```{r}
munster_query <- opq("Münster, Germany") %>% 
  add_osm_feature(key = "boundary", value = "administrative") %>% 
  add_osm_feature(key = "name", value = "Münster") %>% 
  osmdata_sf()

munster_boundary <- munster_query$osm_multipolygons %>% st_transform(st_crs(imperv_20m[[1]]))

p = st_as_sfc(st_bbox(munster_boundary))

munster <- st_crop(imperv_20m[[1]], p)

```


```{r}
imperv_20m = lapply(imp20m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})
for (i in 1:length(imperv_20m)){
  imperv_20m[[i]][is.na(imperv_20m[[i]])] <- 0
}

imp_fraction_20m = lapply(imperv_20m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_20m) <- year
imp_fraction_20m
```
```{r}
imperv_40m = lapply(imp40m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})

# Correct offset in 2018 causing chaos
imperv_40m[[5]] <- read_stars(imp40m_files[[5]], NA_value = 250, proxy = FALSE) %>% setNames("values")

dims <- st_dimensions(imperv_40m[[5]])

dims$x$offset <- st_dimensions(imperv_40m[[4]])$x$offset
dims$y$offset <- st_dimensions(imperv_40m[[4]])$y$offset

st_dimensions(imperv_40m[[5]]) <- dims

imperv_40m[[5]] <- st_crop(imperv_40m[[5]], p)

for (i in 1:length(imperv_40m)){
  imperv_40m[[i]][is.na(imperv_40m[[i]])] <- 0
}

# Calculate the imperviousness fraction
imp_fraction_40m = lapply(imperv_40m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_40m) <- year
imp_fraction_40m

ggplot() +
  #geom_sf(data = t, fill = NA, color = "red") +
  geom_sf(data = p, fill = "lightgreen", color = "darkgreen") +
  #geom_sf(data = imperv_40m[[5]], fill = "red", alpha = 0.5, color = "red", size = 1) +
  geom_tile(data = na.omit(as.data.frame(imperv_8000m[[5]]), xy = TRUE), aes(x = x, y = y, fill = values)) +   # Raster
  geom_tile(data = na.omit(as.data.frame(imperv_8000m[[4]]), xy = TRUE), aes(x = x, y = y, fill = values)) +   # Raster
  theme_minimal() +
  ggtitle("PRODES Deforestation Polygon Overlaid on Brazil - Year 2002")

```

```{r}
imperv_80m = lapply(imp80m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})

# Correct offset in 2018 causing chaos
imperv_80m[[5]] <- read_stars(imp80m_files[[5]], NA_value = 250, proxy = FALSE) %>% setNames("values")

dims <- st_dimensions(imperv_80m[[5]])

dims$x$offset <- st_dimensions(imperv_80m[[4]])$x$offset
dims$y$offset <- st_dimensions(imperv_80m[[4]])$y$offset

st_dimensions(imperv_80m[[5]]) <- dims

imperv_80m[[5]] <- st_crop(imperv_80m[[5]], p)

for (i in 1:length(imperv_80m)){
  imperv_80m[[i]][is.na(imperv_80m[[i]])] <- 0
}

imp_fraction_80m = lapply(imperv_80m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_80m) <- year
imp_fraction_80m
```

```{r}
imperv_100m = lapply(imp100m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})

# Correct offset in 2018 causing chaos
imperv_100m[[5]] <- read_stars(imp100m_files[[5]], NA_value = 250, proxy = FALSE) %>% setNames("values")

dims <- st_dimensions(imperv_100m[[5]])

dims$x$offset <- st_dimensions(imperv_100m[[4]])$x$offset
dims$y$offset <- st_dimensions(imperv_100m[[4]])$y$offset

st_dimensions(imperv_100m[[5]]) <- dims

imperv_100m[[5]] <- st_crop(imperv_100m[[5]], p)

for (i in 1:length(imperv_100m)){
  imperv_100m[[i]][is.na(imperv_100m[[i]])] <- 0
}

imp_fraction_100m = lapply(imperv_100m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_100m) <- year
imp_fraction_100m
```

```{r}
imperv_200m = lapply(imp200m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})

# Correct offset in 2018 causing chaos
imperv_200m[[5]] <- read_stars(imp200m_files[[5]], NA_value = 250, proxy = FALSE) %>% setNames("values")

dims <- st_dimensions(imperv_200m[[5]])

dims$x$offset <- st_dimensions(imperv_200m[[4]])$x$offset
dims$y$offset <- st_dimensions(imperv_200m[[4]])$y$offset

st_dimensions(imperv_200m[[5]]) <- dims

imperv_200m[[5]] <- st_crop(imperv_200m[[5]], p)

for (i in 1:length(imperv_200m)){
  imperv_200m[[i]][is.na(imperv_200m[[i]])] <- 0
}

imp_fraction_200m = lapply(imperv_200m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_200m) <- year
imp_fraction_200m
```

```{r}
imperv_400m = lapply(imp400m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})

# Correct offset in 2018 causing chaos
imperv_400m[[5]] <- read_stars(imp400m_files[[5]], NA_value = 250, proxy = FALSE) %>% setNames("values")

dims <- st_dimensions(imperv_400m[[5]])

dims$x$offset <- st_dimensions(imperv_400m[[4]])$x$offset
dims$y$offset <- st_dimensions(imperv_400m[[4]])$y$offset

st_dimensions(imperv_400m[[5]]) <- dims

imperv_400m[[5]] <- st_crop(imperv_400m[[5]], p)

for (i in 1:length(imperv_400m)){
  imperv_400m[[i]][is.na(imperv_400m[[i]])] <- 0
}

imp_fraction_400m = lapply(imperv_400m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_400m) <- year
imp_fraction_400m
```

```{r}
imperv_800m = lapply(imp800m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})

# Correct offset in 2018 causing chaos
imperv_800m[[5]] <- read_stars(imp800m_files[[5]], NA_value = 250, proxy = FALSE) %>% setNames("values")

dims <- st_dimensions(imperv_800m[[5]])

dims$x$offset <- st_dimensions(imperv_800m[[4]])$x$offset
dims$y$offset <- st_dimensions(imperv_800m[[4]])$y$offset

st_dimensions(imperv_800m[[5]]) <- dims

imperv_800m[[5]] <- st_crop(imperv_800m[[5]], p)

for (i in 1:length(imperv_800m)){
  imperv_800m[[i]][is.na(imperv_800m[[i]])] <- 0
}

imp_fraction_800m = lapply(imperv_800m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_800m) <- year
imp_fraction_800m
```

```{r}
imperv_1000m = lapply(imp1000m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})

# Correct offset in 2018 causing chaos
imperv_1000m[[5]] <- read_stars(imp1000m_files[[5]], NA_value = 250, proxy = FALSE) %>% setNames("values")

dims <- st_dimensions(imperv_1000m[[5]])

dims$x$offset <- st_dimensions(imperv_1000m[[4]])$x$offset
dims$y$offset <- st_dimensions(imperv_1000m[[4]])$y$offset

st_dimensions(imperv_1000m[[5]]) <- dims

imperv_1000m[[5]] <- st_crop(imperv_1000m[[5]], p)

for (i in 1:length(imperv_1000m)){
  imperv_1000m[[i]][is.na(imperv_1000m[[i]])] <- 0
}

imp_fraction_1000m = lapply(imperv_1000m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_1000m) <- year
imp_fraction_1000m
```

```{r}
imperv_2000m = lapply(imp2000m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})

# Correct offset in 2018 causing chaos
imperv_2000m[[5]] <- read_stars(imp2000m_files[[5]], NA_value = 250, proxy = FALSE) %>% setNames("values")

dims <- st_dimensions(imperv_2000m[[5]])

dims$x$offset <- st_dimensions(imperv_2000m[[4]])$x$offset
dims$y$offset <- st_dimensions(imperv_2000m[[4]])$y$offset

st_dimensions(imperv_2000m[[5]]) <- dims

imperv_2000m[[5]] <- st_crop(imperv_2000m[[5]], p)

for (i in 1:length(imperv_2000m)){
  imperv_2000m[[i]][is.na(imperv_2000m[[i]])] <- 0
}

imp_fraction_2000m = lapply(imperv_2000m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_2000m) <- year
imp_fraction_2000m
```

```{r}
imperv_4000m = lapply(imp4000m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})

# Correct offset in 2018 causing chaos
imperv_4000m[[5]] <- read_stars(imp4000m_files[[5]], NA_value = 250, proxy = FALSE) %>% setNames("values")

dims <- st_dimensions(imperv_4000m[[5]])

dims$x$offset <- st_dimensions(imperv_4000m[[4]])$x$offset
dims$y$offset <- st_dimensions(imperv_4000m[[4]])$y$offset

st_dimensions(imperv_4000m[[5]]) <- dims

imperv_4000m[[5]] <- st_crop(imperv_4000m[[5]], p)

for (i in 1:length(imperv_4000m)){
  imperv_4000m[[i]][is.na(imperv_4000m[[i]])] <- 0
}

imp_fraction_4000m = lapply(imperv_4000m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_4000m) <- year
imp_fraction_4000m
```

```{r}
imperv_8000m = lapply(imp8000m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})

# Correct offset in 2018 causing chaos
imperv_8000m[[5]] <- read_stars(imp8000m_files[[5]], NA_value = 250, proxy = FALSE) %>% setNames("values")

dims <- st_dimensions(imperv_8000m[[5]])

dims$x$offset <- st_dimensions(imperv_8000m[[4]])$x$offset
dims$y$offset <- st_dimensions(imperv_8000m[[4]])$y$offset

st_dimensions(imperv_8000m[[5]]) <- dims

imperv_8000m[[5]] <- st_crop(imperv_8000m[[5]], p)

for (i in 1:length(imperv_8000m)){
  imperv_8000m[[i]][is.na(imperv_8000m[[i]])] <- 0
}

imp_fraction_8000m = lapply(imperv_8000m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_8000m) <- year
imp_fraction_8000m
```

```{r}
imperv_10000m = lapply(imp10000m_files, function(file) {read_stars(file, NA_value = 250, proxy = FALSE) %>%  st_crop(p) %>% setNames("values")})

# Correct offset in 2018 causing chaos
imperv_10000m[[5]] <- read_stars(imp10000m_files[[5]], NA_value = 250, proxy = FALSE) %>% setNames("values")

dims <- st_dimensions(imperv_10000m[[5]])

dims$x$offset <- st_dimensions(imperv_10000m[[4]])$x$offset
dims$y$offset <- st_dimensions(imperv_10000m[[4]])$y$offset

st_dimensions(imperv_10000m[[5]]) <- dims

imperv_10000m[[5]] <- st_crop(imperv_1000m[[5]], p)

for (i in 1:length(imperv_10000m)){
  imperv_10000m[[i]][is.na(imperv_10000m[[i]])] <- 0
}

imp_fraction_10000m = lapply(imperv_10000m, function(object) mean(object$values))

year = c(2006, 2009, 2012, 2015, 2018)
names(imp_fraction_10000m) <- year
imp_fraction_10000m
```
  
```{r}
cs <- c("20","40", "80", "100", "200", "400", "800", "1000", "2000", "4000", "8000", "10000")

for (size in cs) {
  files_var <- paste0("imp", size, "m_files")
  files <- get(files_var)
  imperv_var <- paste0("imperv_", size, "m")
  ffmean_var <- paste0("ffmean_", size, "m")
  assign(imperv_var, lapply(files, function(file) read_stars(file, NA_value = 250, proxy = FALSE) %>% st_crop(p) %>% setNames("values")))
  print(get(imperv_var))

  for (i in 1:length(imperv_var)){
    new <- get(imperv_var)
    new[is.na(new)] <- 0
    assign(ffmean_var[i], mean(new$values))
  }
  names(get(ffmean_var)) <- year
  print(get(ffmean_var))
  }
```

```{r}
calc_f <- function(cellsize, se) {
  y <- as.numeric(imp_fraction_20m)
  e <- se[[as.character(cellsize)]][[1]]
  data.frame(
    year <- c(2006, 2009, 2012, 2015, 2018),
    ref = imp_fraction_20m,
    cellsize = as.numeric(cellsize)[1],
    fraction = y,
    err = e,
    emin = pmax(0, y-2*e),
    emax = pmin(.3, y+2*e)
  )
}

all <- do.call(rbind, mapply(calc_f, cs, se_mc, SIMPLIFY=FALSE))
```

```{r}
y <- as.numeric(imp_fraction_20m)
e <- se_mc[[as.character(cs[[1]])]]
year <- c(2006, 2009, 2012, 2015, 2018)
ref = as.numeric(imp_fraction_20m)
fraction = y
err = e
emin = pmax(0, y-2*e)
emax = pmin(.3, y+2*e)

cellsize_to_plot <- 20

ggplot() +
  geom_line(aes(y = ref), lwd = 3, color = 'grey') +
  geom_point(aes(y = fraction), color = "blue") +
  geom_line(aes(y = fraction), linetype = 2, color = "blue") +
  geom_errorbar(aes(ymin = fraction - 2 * err, ymax = fraction + 2 * err), width = 0.2) +
  geom_errorbar(aes(ymin = emin, ymax = emax), width = 0.2, color = "black") +
  labs(
    title = paste(as.character(cs[[1]]), "m regular sampling"),
    x = "Year",
    y = "Forest Cover (fraction)"
  ) +
  #ylim(0, 0.3) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))
```
```{r}
tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res20m_MC.tiff)", units="in", width=10, height=6, res=1200)

cellsize <- as.numeric(cs)[1]

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_20m)
e = c(se_mc2006["20"], se_mc2009["20"], se_mc2012["20"], se_mc2015["20"], se_mc2018["20"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res20m_GQ.tiff)", units="in", 
width=10, height=6, res=1200)
year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_20m)
e = c(se_gq2006["20"], se_gq2009["20"], se_gq2012["20"], se_gq2015["20"], se_gq2018["20"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))

dev.off()
```

```{r}
cellsize <- as.numeric(cs)[2]

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res40m_MC.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_40m)
e = c(se_mc2006["40"], se_mc2009["40"], se_mc2012["40"], se_mc2015["40"], se_mc2018["40"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res40m_GQ.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_40m)
e = c(se_gq2006["40"], se_gq2009["40"], se_gq2012["40"], se_gq2015["40"], se_gq2018["40"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))


dev.off()
```

```{r}
cellsize <- as.numeric(cs)[3]

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res80m_MC.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_80m)
e = c(se_mc2006["80"], se_mc2009["80"], se_mc2012["80"], se_mc2015["80"], se_mc2018["80"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res80m_GQ.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_80m)
e = c(se_gq2006["80"], se_gq2009["80"], se_gq2012["80"], se_gq2015["80"], se_gq2018["80"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))


dev.off()
```

```{r}
cellsize <- as.numeric(cs)[4]

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res100m_MC.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_100m)
e = c(se_mc2006["100"], se_mc2009["100"], se_mc2012["100"], se_mc2015["100"], se_mc2018["100"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res100m_GQ.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_100m)
e = c(se_gq2006["100"], se_gq2009["100"], se_gq2012["100"], se_gq2015["100"], se_gq2018["100"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))


dev.off()
```

```{r}
cellsize <- as.numeric(cs)[5]

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res200m_MC.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_200m)
e = c(se_mc2006["200"], se_mc2009["200"], se_mc2012["200"], se_mc2015["200"], se_mc2018["200"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res200m_GQ.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_200m)
e = c(se_gq2006["200"], se_gq2009["200"], se_gq2012["200"], se_gq2015["200"], se_gq2018["200"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))


dev.off()
```

```{r}
cellsize <- as.numeric(cs)[6]

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res400m_MC.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_400m)
e = c(se_mc2006["400"], se_mc2009["400"], se_mc2012["400"], se_mc2015["400"], se_mc2018["400"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res400m_GQ.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_400m)
e = c(se_gq2006["400"], se_gq2009["400"], se_gq2012["400"], se_gq2015["400"], se_gq2018["400"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))


dev.off()
```

```{r}
cellsize <- as.numeric(cs)[7]

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res800m_MC.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_800m)
e = c(se_mc2006["800"], se_mc2009["800"], se_mc2012["800"], se_mc2015["800"], se_mc2018["800"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res800m_GQ.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_800m)
e = c(se_gq2006["800"], se_gq2009["800"], se_gq2012["800"], se_gq2015["800"], se_gq2018["800"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))


dev.off()
```

```{r}
cellsize <- as.numeric(cs)[8]

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res1000m_MC.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_1000m)
e = c(se_mc2006["1000"], se_mc2009["1000"], se_mc2012["1000"], se_mc2015["1000"], se_mc2018["1000"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res1000m_GQ.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_1000m)
e = c(se_gq2006["1000"], se_gq2009["1000"], se_gq2012["1000"], se_gq2015["1000"], se_gq2018["1000"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))


dev.off()
```

```{r}
cellsize <- as.numeric(cs)[9]

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res2000m_MC.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_2000m)
e = c(se_mc2006["2000"], se_mc2009["2000"], se_mc2012["2000"], se_mc2015["2000"], se_mc2018["2000"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res2000m_GQ.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_2000m)
e = c(se_gq2006["2000"], se_gq2009["2000"], se_gq2012["2000"], se_gq2015["2000"], se_gq2018["2000"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))

dev.off()
```

```{r}
cellsize <- as.numeric(cs)[10]

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res4000m_MC.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_4000m)
e = c(se_mc2006["4000"], se_mc2009["4000"], se_mc2012["4000"], se_mc2015["4000"], se_mc2018["4000"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res4000m_GQ.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_4000m)
e = c(se_gq2006["4000"], se_gq2009["4000"], se_gq2012["4000"], se_gq2015["4000"], se_gq2018["4000"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))

dev.off()
```

```{r}
cellsize <- as.numeric(cs)[11]

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res8000m_MC.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_8000m)
e = c(se_mc2006["8000"], se_mc2009["8000"], se_mc2012["8000"], se_mc2015["8000"], se_mc2018["8000"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res8000m_GQ.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_8000m)
e = c(se_gq2006["8000"], se_gq2009["8000"], se_gq2012["8000"], se_gq2015["8000"], se_gq2018["8000"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))

dev.off()
```

```{r}
cellsize <- as.numeric(cs)[12]

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res10000m_MC.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_10000m)
e = c(se_mc2006["10000"], se_mc2009["10000"], se_mc2012["10000"], se_mc2015["10000"], se_mc2018["10000"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Monte-Carlo"))

tiff(r"(C:\Users\yeid\Documents\Dead Laptop Files\Documents\1b. PhD\2. On-going Publications\1. Downsampling\Downsampled_Output\Graphs\Res10000m_GQ.tiff)", units="in", width=10, height=6, res=1200)

year <- c(2006, 2009, 2012, 2015, 2018)
x <- imp_fraction_20m
y <- as.numeric(imp_fraction_10000m)
e = c(se_gq2006["10000"], se_gq2009["10000"], se_gq2012["10000"], se_gq2015["10000"], se_gq2018["10000"])
#ylim = c(min(0.2, min(y) - 2 * e), max(0.2, max(y) + 2 * e))
ylim = c(-0.2, 0.5)
plot(year, x, type = 'l', ylim = ylim, col = 'grey', lwd = 7, ylab = "Imperviousness Fraction", xlab = "Year")
lines(year, y, type = 'b')
arrows(x0=year, y0=y-2*e, x1=year, y1=y+2*e, code=3, angle=90, length = 0.1, col="black")
title(paste(cellsize, "m regular sampling w/ Gauss-Quadrature"))


dev.off()
```
